config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  root to: 'sessions#new'

  # ** Routes for Errors **
  match "/404", :to => "exception#not_found", :via => :all
  match "/500", :to => "exception#internal_server_error", :via => :all

  # ** Routes for public visitors **

  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about', to: 'pages#about'
  get 'interest', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-and-conditions', to: 'pages#terms_and_conditions'

  post 'interest', to: 'contacts#interest'
  post 'enquiry', to: 'contacts#enquiry'

  resources :registrations, only: [:new, :create] do
    get :confirm_email, on: :member
  end

  resources :password_resets, only: [:create, :edit, :update]

  # ** Routes for users with accounts **
  resources :opportunities

  resources :events do
    patch :add_to_profile, on: :member
  end

  resources :artists, only: [:index, :show] do
    resources :series, only: [:show]
    resources :artworks, only: [:show, :index]
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :professionals, only: [:index, :show] do
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :companies, only: [:index, :show], path: 'organisations/' do
    patch :join, on: :member
    patch :leave, on: :member
    patch :follow, on: :member
    patch :unfollow, on: :member
  end

  resources :locations, only: [:show]

  namespace :my do
    resource :tags, only: [:create]

    resource :invite, only: [:create]

    resource :feed, only: [:show]

    resource :profile, only: [:edit, :update]

    resource :settings, only: [:show, :update] do
      get :account
      put :deactivate, on: :member
    end

    resource :password, only: [:show, :update]

    resources :connections, only: [:index, :create, :destroy] do
      put :accept, on: :member
      put :reject, on: :member
    end

    resources :companies, only: [:index, :show, :new, :create, :edit, :update], path: 'organisations/' do
      resources :memberships, only: [:create] do
        delete :destroy, on: :collection
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end
  end

  # ** Routes for users with an artist profile **

  namespace :portfolio do
    resources :artwork_collaborators, only: [] do
      patch :accept, on: :member
      patch :reject, on: :member
    end

    resources :series  do
      get :rearrange, on: :member
      patch :set_order, on: :member
      patch :set_cover, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member

      resources :artworks, only: [:index, :update, :destroy] do
        delete :bulk_destroy, on: :collection
        patch :bulk_update, on: :collection
        post :document_bulk_upload, on: :collection
      end
    end

    resources :artworks, only: [] do
      get :upload, on: :collection
      post :bulk_upload, on: :collection
      post :bulk_group, on: :collection
    end
  end

  # ** Routes for administrators **

  namespace :admin do
    namespace :audits do
      resources :media, :subjects, :specialisations do
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end

    resources :companies, only: [:index, :edit, :update], path: 'organisations/'

    resources :events, only: :index

    resources :users, only: [:index, :show] do
      put :activate, on: :member
      put :deactivate, on: :member
    end

    resources :feeds, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/specialisation.rb
class Specialisation < ActiveRecord::Base

  belongs_to :user

  enum state: [:pending, :approved, :rejected]

  validates :name, presence: true

end

app/controllers/admin/audits/media_controller.rb
class Admin::Audits::MediaController < Admin::BaseController
  before_action :find_medium, only: [:edit, :update, :approve, :reject]

  def index
    media = Medium.order(:state)
    @media = media.map { |medium| UserDecorator.new(medium) }
  end

  def edit
  end

  def update
    if @medium.update(medium_params)
      redirect_to admin_audits_media_path
    else
      flash[:error] = @medium.errors.full_messages
      render :edit
    end
  end

  def approve
    if @medium.update(state: 1, action_date: Date.current)
      flash[:notice] = 'Tag is approved'
      redirect_to admin_audits_media_path
    else
      flash[:notice] = 'Error approving.'
    end
  end

  def reject
    if @medium.update(state: 2, action_date: Date.current)
      flash[:notice] = 'Tag is rejected'
      redirect_to admin_audits_media_path
    else
      flash[:notice] = 'Error saving.'
    end
  end

  private

  def medium_params
    params.require(:medium).permit(:name, :name_edit_date, :state)
  end

  def find_medium
    @medium = Medium.find(params[:id])
  end
end

app/controllers/admin/audits/specialisations_controller.rb
class Admin::Audits::SpecialisationsController < Admin::BaseController

  before_action :find_specialisation, only: [:edit, :update, :approve, :reject]

  def index
    specialisations = Specialisation.order(:state)
    @specialisations = specialisations.map { |a| UserDecorator.new(a) }
  end

  def edit
  end

  def update
    if @specialisation.update(specialisation_params)
      redirect_to admin_audits_specialisations_path
    else
      flash[:error] = @specialisation.errors.full_messages
      render :edit
    end
  end

  def approve
    if @specialisation.update(state: 1, action_date: Date.current)
      flash[:notice] = 'Tag is approved'
      redirect_to admin_audits_specialisations_path
    else
      flash[:notice] = 'Error approving'
    end
  end

  def reject
    if @specialisation.update(state: 2, action_date: Date.current)
      flash[:notice] = 'Tag is rejected'
      redirect_to admin_audits_specialisations_path
    else
      flash[:notice] = 'Error rejecting'
    end
  end

  private

  def specialisation_params
    params.require(:specialisation).permit(:name, :name_edit_date, :state)
  end

  def find_specialisation
    @specialisation = Specialisation.find(params[:id])
  end
end

app/controllers/admin/audits/subjects_controller.rb
class Admin::Audits::SubjectsController < Admin::BaseController

  before_action :find_subject, only: [:edit, :update, :approve, :reject]

  def index
    subjects = Subject.order(:state)
    @subjects = subjects.map { |a| UserDecorator.new(a) }
  end

  def edit
  end

  def update
    if @subject.update(subject_params)
      redirect_to admin_audits_subjects_path
    else
      flash[:error] = @subject.errors.full_messages
      render :edit
    end
  end

  def approve
    if @subject.update(state: 1, action_date: Date.current)
      flash[:notice] = 'Tag is approved'
      redirect_to admin_audits_subjects_path
    else
      flash[:notice] = 'Error approving'
    end
  end

  def reject
    if @subject.update(state: 2, action_date: Date.current)
      flash[:notice] = 'Tag is rejected'
      redirect_to admin_audits_subjects_path
    else
      flash[:notice] = 'Error rejecting'
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :name_edit_date, :state)
  end

  def find_subject
    @subject = Subject.find(params[:id])
  end
end

app/views/admin/audits/specialisations/edit.html.slim
.row
  .col-xs-12
  h2 Edit #{@specialisation.name}
  = simple_form_for @specialisation, url: { action: 'update' } do |f|
    = f.input :name, input_html: { value: f.object.name.titleize }
    = f.input :state, as: :select, collection: options_for_enum(Specialisation.states), prompt: 'Please Select'
    = f.button :submit
    = f.input :name_edit_date, as: :hidden, input_html: { value: Date.today }
    = link_to 'Back', admin_audits_specialisations_path, class: 'btn btn-default pull-right'

app/views/admin/audits/specialisations/index.html.slim
.row
  .col-xs-1
    = render partial: 'admin/menubar'
  .col-xs-11
    ul.nav.nav-tabs
      li role='presentation'
        = link_to 'Audit Media', admin_audits_media_path
      li role='presentation'
        = link_to 'Audit Subjects', admin_audits_subjects_path
      li.active role= 'presentation'
        = link_to 'Audit Specialisations', admin_audits_specialisations_path

    h3 Subjects & Themes
    .table-responsive
      table.table.table-hover
        thead
          tr
            th Tag Name
            th User Name
            th Status
            th Approve/Reject Date
            th Tag Name Last Updated
            th Action

        tbody
          - @specialisations.each do |specialisation|
            tr
              td = specialisation.name.titleize
              td = specialisation.tag_user_full_name.titleize
              td = specialisation.state.humanize
              td = specialisation.action_date
              td = specialisation.name_edit_date
              td = link_to 'Edit', edit_admin_audits_specialisation_path(specialisation), class: 'btn btn-secondary'
              - if specialisation.pending?
                td = link_to 'Approve', approve_admin_audits_specialisation_path(specialisation), method: :patch, class: 'btn btn-default'
                td = link_to 'Reject', reject_admin_audits_specialisation_path(specialisation), method: :patch, class: 'btn btn-primary'