config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  root to: 'sessions#new'

  # ** Routes for Errors **
  match "/404", :to => "exception#not_found", :via => :all
  match "/500", :to => "exception#internal_server_error", :via => :all

  # ** Routes for public visitors **

  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about', to: 'pages#about'
  get 'interest', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-and-conditions', to: 'pages#terms_and_conditions'

  post 'interest', to: 'contacts#interest'
  post 'enquiry', to: 'contacts#enquiry'

  resources :registrations, only: [:new, :create] do
    get :confirm_email, on: :member
  end

  resources :password_resets, only: [:create, :edit, :update]

  # ** Routes for users with accounts **
  resources :opportunities

  resources :events do
    patch :add_to_profile, on: :member
  end

  resources :artists, only: [:index, :show] do
    resources :series, only: [:show]
    resources :artworks, only: [:show, :index]
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :professionals, only: [:index, :show] do
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :companies, only: [:index, :show], path: 'organisations/' do
    patch :join, on: :member
    patch :leave, on: :member
    patch :follow, on: :member
    patch :unfollow, on: :member
  end

  resources :locations, only: [:show]

  namespace :my do
    resource :tags, only: [:create]

    resource :invite, only: [:create]

    resource :feed, only: [:show]

    resource :profile, only: [:edit, :update]

    resource :settings, only: [:show, :update] do
      get :account
      put :deactivate, on: :member
    end

    resource :password, only: [:show, :update]

    resources :connections, only: [:index, :create, :destroy] do
      put :accept, on: :member
      put :reject, on: :member
    end

    resources :companies, only: [:index, :show, :new, :create, :edit, :update], path: 'organisations/' do
      resources :memberships, only: [:create] do
        delete :destroy, on: :collection
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end
  end

  # ** Routes for users with an artist profile **

  namespace :portfolio do
    resources :artwork_collaborators, only: [] do
      patch :accept, on: :member
      patch :reject, on: :member
    end

    resources :series  do
      get :rearrange, on: :member
      patch :set_order, on: :member
      patch :set_cover, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member

      resources :artworks, only: [:index, :update, :destroy] do
        delete :bulk_destroy, on: :collection
        patch :bulk_update, on: :collection
        post :document_bulk_upload, on: :collection
      end
    end

    resources :artworks, only: [] do
      get :upload, on: :collection
      post :bulk_upload, on: :collection
      post :bulk_group, on: :collection
    end
  end

  # ** Routes for administrators **

  namespace :admin do
    namespace :audits do
      resources :media, :subjects, :specialisations do
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end

    resources :companies, only: [:index, :edit, :update], path: 'organisations/'

    resources :events, only: :index

    resources :users, only: [:index, :show] do
      put :activate, on: :member
      put :deactivate, on: :member
    end

    resources :feeds, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user, touch: true

  has_many :language_proficiencies
  has_many :languages, through: :language_proficiencies

  validate :medium_ids_presence, if: Proc.new { |p| p.role == "artist" }

  accepts_nested_attributes_for :language_proficiencies, reject_if: :all_blank, allow_destroy: true

  def media
    Medium.approved.where(id: medium_ids).pluck(:name) rescue []
  end

  def subjects
    Subject.approved.where(id: subject_ids).pluck(:name)
  end

  def interests
    Interest.approved.where(id: interest_ids).pluck(:name)
  end

  def skills
    Skill.approved.where(id: skill_ids).pluck(:name)
  end

  def specialisations
    Specialisation.approved.where(id: specialisation_ids).pluck(:name) rescue []
  end

  def services
    Service.approved.where(id: service_ids).pluck(:name)
  end

  def medium_ids_presence
    if medium_ids.compact.empty?
      errors.add("user: medium_ids", "cant be blank")
    end
  end
end

app/controllers/my/base_controller.rb
module My
  class BaseController < ApplicationController

    JS_ASSETS = %w(application my_companies my_connections my_profiles my_settings).freeze

    before_action :require_login
    before_action :prepare_user

    private

    def prepare_user
      @user = current_user
    end

  end
end

app/controllers/my/companies_controller.rb
module My
  class CompaniesController < My::BaseController

    def index
      @user = UserDecorator.new(@user)
      @companies = current_user.companies.map { |c| CompanyDecorator.new(c) }
    end

    def new
      @company_form = My::CompanyForm.new
    end

    def create
      @company_form = My::CompanyForm.new(company_form_params)

      if @company_form.save
        redirect_to my_companies_path, notice: 'New organisation created! Stay tuned for more features'
      else
        flash[:error] = @company_form.errors.full_messages.to_sentence
        render :new
      end
    end

    def show
      @company_presenter = My::CompanyPresenter.new(user_id: @user.id, company_id: params[:id])
    end

    def edit
      @company = @user.companies.find(params[:id])
      @company_form = My::CompanyForm.new(existing_company: @company)
    end

    def update
      @company = @user.companies.find(params[:id])
      @company_form = My::CompanyForm.new(company_form_params.merge(existing_company: @company))

      if @company_form.save
        redirect_to my_companies_path
      else
        flash[:error] = @company_form.errors.full_messages.to_sentence
        render :edit
      end
    end

    private

    def company_form_params
      params.require(:my_company_form).permit(company_attributes: company_attributes_whitelist).tap do |params|
        params[:company_attributes][:owner_id] = current_user.id
      end
    end

    def company_attributes_whitelist
      [
        :image_url, :name, :motto, :country, :state, :established_in, :address_1, :address_2, :contact, :about_us, :postcode,
        :facebook, :twitter, :instagram, :description, :country, :state, :phone, :email, :location,
        :position, :website, :opening_time, :closing_time, organization_type_ids: []
      ]
    end

  end
end

app/controllers/my/connections_controller.rb
module My
  class ConnectionsController < My::BaseController
    before_action :prepare_friend, only: [:create, :accept, :reject, :destroy]

    def index
      @user = UserDecorator.new(@user)
      @friends = current_user.friends.map { |u| UserDecorator.new(u) }.sort_by(&:name)
      @requests = current_user.pending_friends.map { |p| UserDecorator.new(p) }
    end

    def create
      @connection = current_user.connections.build(friend: @friend)
      if @connection.save
        redirect_to :back, notice: 'Connection has been requested'
      else
        redirect_to :back, alert: 'Connection already requested.'
      end
    end

    def accept
      connection = Connection.find_by(friend_id: current_user.id, user_id: @friend.id)
      if connection.pending?
        connection.accept!
        redirect_to my_connections_path, notice: 'Connection accepted.'
      else
        redirect_to my_connections_path, alert: 'Connection is already accepted.'
      end
    end

    def reject
      connection = Connection.find_by(friend_id: current_user.id, user_id: @friend.id)
      if connection.pending?
        connection.reject!
        redirect_to my_connections_path, notice: 'Connection rejected.'
      else
        redirect_to my_connections_path, alert: 'Connection is already rejected.'
      end
    end

    def destroy
      @connection = current_user.connections.accepted.find_by(friend: @friend) ||
                    current_user.passive_connections.accepted.find_by(user: @friend)
      if @connection&.destroy
        redirect_to my_connections_path, notice: 'Connection Removed'
      else
        redirect_to my_connections_path, alert: 'Connection is already disconnected.'
      end
    end

    private

    def prepare_friend
      @friend = User.find(params[:id])
    end

  end
end

app/controllers/my/feeds_controller.rb
module My
  class FeedsController < My::BaseController
    def show
      friends = @user.friends
      feed_items = FeedItem.includes(:user, :artwork).where(user: friends).order(created_at: :desc)
      @feed_items = FeedItemDecorator.wrap_all(feed_items)
    end
  end
end

app/controllers/my/invites_controller.rb
module My
  class InvitesController < My::BaseController
    def create
      @invite = InvitationMailer.invite(params[:email], params[:full_name], @user).deliver_later
      redirect_to root_path, notice: "Your invite to #{params[:full_name]} (#{params[:email]}) was successfully sent!"
    end
  end
end

app/controllers/my/memberships_controller.rb
module My
  class MembershipsController < My::BaseController

    before_action :set_company, only: [:create, :destroy, :approve, :reject]

    def create
      @membership = @company.company_memberships.build(user_id: params[:user_id])
      if @membership.save
        redirect_to my_company_path(@company), notice: 'User added to company!'
      else
        redirect_to my_company_path(@company), alert: 'Something went wrong. Please try again!'
      end
    end

    def destroy
      @membership = @company.company_memberships.find_or_initialize_by(user_id: params[:member_id])

      if !@membership.new_record? && @membership.destroy
        redirect_to my_company_path(@company), notice: 'User was removed from company!'
      else
        redirect_to my_company_path(@company), alert: 'Something went wrong. Please try again!'
      end
    end

    def approve
      @membership = @company.company_memberships.find_by(id: params[:id])

      if @membership.approve!
        redirect_to :back, notice: 'User approved!'
      else
        redirect_to :back, alert: 'Something went wrong. Please try again!'
      end
    end

    def reject
      @membership = @company.company_memberships.find_by(id: params[:id])

      if @membership.reject!
        redirect_to :back, notice: 'User rejected!'
      else
        redirect_to :back, alert: 'Something went wrong. Please try again!'
      end
    end

    private

    def set_company
      @company = @user.companies.find(params[:company_id])
    end

  end
end

app/controllers/my/passwords_controller.rb
module My
  class PasswordsController < My::BaseController
    before_action :authenticate_user, only: [:update]

    def show
    end

    def update
      if @user.update(user_params.except(:current_password))
        redirect_to my_settings_path, notice: 'Your password has been changed'
      else
        redirect_to my_settings_path, alert: 'Passwords do not match!'
      end
    end

    private

    def user_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end

    def authenticate_user
      @user = User.authenticate(current_user.email, user_params[:current_password])
      redirect_to my_settings_path, alert: 'Current password does not match!' unless @user.present?
    end
  end
end

app/controllers/my/profiles_controller.rb
module My
  class ProfilesController < My::BaseController

    def edit
      @user = ProfilePresenter.new(@user.id).user
      @profile_form = My::ProfileForm.new(@user)
    end

    def update
      update_service_call = UpdateUserService.new(@user, user_params).call

      if update_service_call.success?
        redirect_to @user.artist? ? artist_path(@user) : professional_path(@user), notice: 'Your profile has been updated'
      else
        flash[:error] = " Please review your form and make sure all fields marked as red are not empty"
        redirect_to edit_my_profile_path(errors: @user.errors.messages)
      end
    end

    private

    def user_params
      params.require(:my_profile_form).permit(
        user_attributes: [
          :tagline, :profile_image_url, :statement, :link, :interest, :skills, :language, :language_level, :current_status, :commission, :facebook_link, :twitter_link, :instagram_link, :institution, :education_level, :education_grade, :exhibit_country, :based_state, :based_country, :based_location, :nationality_country, :field_of_study, :residency_status, :other_status,
          artist_status_text: [],
          professional_status_text: [],
          representative_ids: [],
          educations_attributes: [:current, :location, :start_month, :start_year, :end_month, :end_year, :institution, :other_institution, :education_level, :education_grade, :field_of_study, :education_description, :state, :country, :id, :_destroy],
          awards_attributes: [:location, :title, :month, :year, :country, :state, :awarding_body, :prize, :pdf_url, :id, :_destroy],
          residencies_attributes: [:location, :start_month, :start_year, :end_month, :end_year, :current, :body, :title, :country, :state, :id, :_destroy],
          experiences_attributes: [:location, :start_month, :start_year, :end_month, :end_year, :current, :position, :company_id, :state, :country, :category, :job_type, :description, :link, :id, :company_name, :_destroy],
          exhibitions_attributes: [:pdf_filename, :location, :involvement_string, :record_start_year, :record_end_year, :start_month, :end_month, :start_year, :end_year, :title, :category, :venue_id, :state, :country, :pdf_url, :id, :_destroy],
          bibliographies_attributes: [:pdf_filename, :volume, :review_of, :location, :title, :publication_title, :publisher, :edition, :author, :page_number, :source_type, :link, :participation, :publication_city, :publication_country, :editor, :issue, :pdf_url, :attachment_url, :day, :month, :year, :id, :_destroy],
          publications_attributes: [:pdf_filename, :location, :volume, :review_of, :participation, :category, :title, :publication_title, :country, :state, :day, :month, :year, :publisher, :edition, :editor, :issue, :page_numbers, :link, :pdf_url, :attachment_url, :id, :_destroy],
          participations_attributes: [:month, :year, :title, :description, :link, :id, :_destroy],
          collections_attributes: [:name, :id, :_destroy],
          memberships_attributes: [:name, :start_date, :end_date, :id, :_destroy],
          media_features_attributes: [:month, :year, :title, :description, :link, :id, :_destroy],
          profile_attributes: [
            :id,
            medium_ids: [],
            subject_ids: [],
            interest_ids: [],
            skill_ids: [],
            specialisation_ids: [],
            service_ids: [],
            language_proficiencies_attributes: [:id, :language_id, :level, :_destroy]
          ]
        ]
      )
    end
  end

end

app/controllers/my/settings_controller.rb
module My
  class SettingsController < My::BaseController

    def show
    end

    def update
      if @user.update_attributes(user_params)
        redirect_to my_settings_path, notice: 'Your settings have been updated!'
      else
        flash[:error] = 'Please check your form again and re-submit'
        render :show
      end
    end

    def account
    end

    def deactivate
      @user.update_attributes(active: false, reason_deactivating: params[:user][:reason_deactivating])
      logout
      redirect_to root_path, notice: 'Your account has successfully been deactivated'
    end

    private

    def user_params
      params.require(:user).permit(
        :email, :password, :password_confirmation, :title,
        :first_name, :initial, :last_name, :date_of_birth
      )
    end

  end
end

app/controllers/my/tags_controller.rb
module My
  class TagsController < My::BaseController
    ALLOWED_TAGS = %w(Medium Subject Specialisation Skill Language Service OrganizationType Company).freeze

    before_action :whitelist_tag, only: [:create]

    def create
      if @klass
        build_klass
        if @tag.save
          render json: @tag.to_json
        else
          redirect_to root_path, alert: 'This tag is invalid'
        end
      else
        redirect_to root_path, alert: 'This tag type is not available'
      end
    end

    private

    def whitelist_tag
      return if params[:klass].blank?
      @klass = ALLOWED_TAGS.grep(params[:klass]).first&.safe_constantize
    end

    def build_klass
      @tag = if @klass == Company
               @klass.new(name: params[:name])
             else
               @klass.new(user_id: @user.id, name: params[:name])
             end
    end

  end
end

app/views/my/profiles/_award_fields.html.slim
fieldset.nested-fields
  = f.hidden_field :_destroy, value: false, class: "destroy-me"
  hr.-thin
  .row
    .col-xs-4
      .form-inline
        = f.input :month, label: false, collection: Month.collection_options, prompt: 'Month*', input_html: { class: "month #{ 'error' if params[:errors].present? && params[:errors]['awards.month'].present?}" }, required: true
        = f.input :year, label: false, collection: Year.collection_options, prompt: 'Year*', input_html: { class: "#{ 'error' if params[:errors].present? && params[:errors]['awards.year'].present?}" }, required: true
    .col-xs-6
      = f.input :awarding_body, label: false, placeholder: 'Awarding Body*', input_html: { class: "#{ 'error' if params[:errors].present? && params[:errors]['awards.awarding_body'].present?}" }, required: true
      = f.input :title, label: false, placeholder: 'Title*', input_html: { class: "#{ 'error' if params[:errors].present? && params[:errors]['awards.title'].present?}" }, required: true
      = f.input :location, placeholder: "Enter city or country", label: false, input_html: { class: "google-places-autocomplete-award" }
      = f.hidden_field :state, class: "location-state-award"
      = f.hidden_field :country, class: "location-country-award"
    .col-xs-12
      = link_to_remove_association fa_icon('minus').html_safe + ' Remove', f

app/views/my/profiles/_exhibition_fields.html.slim
fieldset.nested-fields
  = f.hidden_field :_destroy, value: false, class: "destroy-me"
  hr.-thin
  - if f.object.new_record? || f.object.pdf_url.present?
    .row
      .col-xs-4
        .form-inline
          = f.input :record_start_year, label: false, collection: Year.collection_options, prompt: 'Year*', input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.record_start_year'].present?}" }
          span &ndash;
          = f.input :record_end_year, label: false, collection: Year.collection_options, prompt: 'Year*', input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.record_end_year'].present?}" }
      .col-xs-6
        .exhibition-upload
          - if f.object.pdf_url.blank?
            p File Name:
          - else
            p
              = link_to "File Name: #{f.object.pdf_filename}", f.object.pdf_url
          = f.filepicker_field :pdf_url,
            button_text: (f.object.pdf_url.blank? ? 'Upload New PDF' : 'Replace Current PDF'),
            button_class: 'btn btn-default btn-block', extensions: '.pdf', multiple: false,
            onchange: 'exhibitionUpload(event)'
          = f.hidden_field :pdf_filename, class: "exhibition-pdf-filename"

    - if f.object.new_record?
      .row
        .col-xs-6.col-xs-push-4
          p.text-center OR fill in the details below
  - if f.object.new_record? || f.object.pdf_url.blank?
    .row
      .col-xs-4
        .form-inline
          = f.input :start_month, label: false, collection: Month.collection_options, prompt: 'Month*', input_html: { class: "month #{'error' if params[:errors].present? && params[:errors]['exhibitions.start_month'].present?}" }
          = f.input :start_year, label: false, collection: Year.collection_options, prompt: 'Year*', input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.start_year'].present?}" }
          span &ndash;
          = f.input :end_month, label: false, collection: Month.collection_options, prompt: 'Month*', input_html: { class: "month #{'error' if params[:errors].present? && params[:errors]['exhibitions.end_month'].present?}" }
          = f.input :end_year, label: false, collection: Year.collection_options, prompt: 'Year*', input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.end_year'].present?}" }
      .col-xs-6
        / = f.input :involvement_string, label: false, placeholder: 'Involvement', input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.involvement'].present?}" }
        = f.input :title, label: false, placeholder: 'Exhibition Title*', input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.title'].present?}" }
        - if @user.artist?
          = f.input :category, label: false, collection: Exhibition::OPTIONS_FOR_CATEGORY, prompt: 'Type*',
            include_blank: false, input_html: { class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.category'].present?}" }
        = f.association :venue, label: false, prompt: 'Venue*', wrapper: :selectize, input_html: { data: { selectize_company: true, klass: Company.to_s, url: my_tags_path(format: :json) }, class: "#{'error' if params[:errors].present? && params[:errors]['exhibitions.venue'].present?}" }
        = f.input :location, placeholder: "Enter city or country*", label: false, input_html: { class: "google-places-autocomplete-exhibition" }
        = f.hidden_field :state, class: "location-state-exhibition"
        = f.hidden_field :country, class: "location-country-exhibition"
  = link_to_remove_association fa_icon('minus').html_safe + ' Remove', f

app/views/my/profiles/_language_proficiency_fields.html.slim
.nested-fields
  = f.association :language, as: :select, placeholder: 'Select a language', input_html: { data: { klass: 'Language', url: my_tags_path(format: :json) } }, wrapper: :selectize
  = f.input :level, collection: options_for_enum(LanguageProficiency.levels), prompt: 'Please select'
  = link_to_remove_association 'Remove', f, class: 'btn btn-default'
  hr

app/views/my/profiles/_professional.html.slim
#professional-profile-form-validate
  = simple_form_for(@profile_form, url: my_profile_path, method: :patch) do |f|

    = f.simple_fields_for :user do |user|
      = render 'header', f: user
      = render 'professional_status_fields', f: user

      section.section-3
        .row
          .col-xs-12
            #accordion.panel-group aria-multiselectable='true' role='tablist'
              .panel.panel-default
                #heading-education.panel-heading role='tab' data-toggle='collapse' href='#collapse-education'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-education' aria-expanded='true' data-parent='#accordion' Education
                    = fa_icon 'chevron-down', class: 'indicator pull-right'
                #collapse-education.panel-collapse.collapse.in aria-labelledby='heading-education' role='tabpanel'
                  .panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :educations do |education|
                        = render 'education_fields', f: education
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :educations,
                          class: 'btn btn-default pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-awards.panel-heading role='tab' data-toggle='collapse' href='#collapse-awards'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-awards' aria-expanded='true' data-parent='#accordion' Grants/Fellowships/Awards
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-awards.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-awards' role='tabpanel'
                  #partial-award.panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :awards do |award|
                        = render 'award_fields', f: award
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :awards, class: 'btn btn-default button-link pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-participations.panel-heading role='tab' data-toggle='collapse' href='#collapse-participations'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-participations' aria-expanded='true' data-parent='#accordion' Professional & Community Participation
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-participations.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-participations' role='tabpanel'
                  .panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :participations do |participation|
                        = render 'participation_fields', f: participation
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :participations, class: 'btn btn-default button-link pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-exhibition.panel-heading role='tab' data-toggle='collapse' href='#collapse-exhibition'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-exhibition' aria-expanded='false' data-parent='#accordion' Exhibition Record
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-exhibition.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-exhibition' role='tabpanel'
                  #partial-exhibition.panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :exhibitions do |exhibition|
                        = render 'exhibition_fields', f: exhibition
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :exhibitions, class: 'btn btn-default button-link pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-experience.panel-heading role='tab' data-toggle='collapse' href='#collapse-experience'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-experience' aria-expanded='false' data-parent='#accordion' Professional Experience
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-experience.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-experience' role='tabpanel'
                  #partial-experience.panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :experiences do |experience|
                        = render 'experience_fields', f: experience
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :experiences, class: 'btn btn-default button-link pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-publications.panel-heading role='tab' data-toggle='collapse' href='#collapse-publications'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-publications' aria-expanded='false' data-parent='#accordion' Scholarly & Professional Publications
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-publications.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-publications' role='tabpanel'
                  #partial-publication.panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :publications do |publication|
                        = render 'publication_fields', f: publication
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :publications, class: 'btn btn-default button-link pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-memberships.panel-heading role='tab' data-toggle='collapse' href='#collapse-memberships'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-memberships' aria-expanded='false' data-parent='#accordion' Professional Affliations/Memberships
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-memberships.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-memberships' role='tabpanel'
                  .panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :memberships do |membership|
                        = render 'membership_fields', f: membership
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :memberships, class: 'btn btn-default button-link pull-right adding-another'
              hr.accordion-hr
              .panel.panel-default
                #heading-media.panel-heading role='tab' data-toggle='collapse' href='#collapse-media'
                  h4.panel-title
                    a.collapsed aria-controls='collapse-media' aria-expanded='false' data-parent='#accordion' Media Features
                    = fa_icon 'chevron-up', class: 'indicator pull-right'
                #collapse-media.panel-collapse.collapse class=("in" if params[:errors].present?) aria-labelledby='heading-media' role='tabpanel'
                  .panel-body
                    .row.cocoon-container
                      = user.simple_fields_for :media_features do |media_feature|
                        = render 'media_feature_fields', f: media_feature
                    .row
                      br
                      = link_to_add_association fa_icon('plus').html_safe + ' add another entry', user, :media_features, class: 'btn btn-default button-link pull-right adding-another'
    nav.row
      .cta
        = f.submit 'Save & Done', class: 'btn btn-default'
        = link_to 'Cancel', profile_path(current_user), class: 'btn btn-primary'