config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  root to: 'sessions#new'

  # ** Routes for Errors **
  match "/404", :to => "exception#not_found", :via => :all
  match "/500", :to => "exception#internal_server_error", :via => :all

  # ** Routes for public visitors **

  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about', to: 'pages#about'
  get 'interest', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-and-conditions', to: 'pages#terms_and_conditions'

  post 'interest', to: 'contacts#interest'
  post 'enquiry', to: 'contacts#enquiry'

  resources :registrations, only: [:new, :create] do
    get :confirm_email, on: :member
  end

  resources :password_resets, only: [:create, :edit, :update]

  # ** Routes for users with accounts **
  resources :opportunities

  resources :events do
    patch :add_to_profile, on: :member
  end

  resources :artists, only: [:index, :show] do
    resources :series, only: [:show]
    resources :artworks, only: [:show, :index]
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :professionals, only: [:index, :show] do
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :companies, only: [:index, :show], path: 'organisations/' do
    patch :join, on: :member
    patch :leave, on: :member
    patch :follow, on: :member
    patch :unfollow, on: :member
  end

  resources :locations, only: [:show]

  namespace :my do
    resource :tags, only: [:create]

    resource :invite, only: [:create]

    resource :feed, only: [:show]

    resource :profile, only: [:edit, :update]

    resource :settings, only: [:show, :update] do
      get :account
      put :deactivate, on: :member
    end

    resource :password, only: [:show, :update]

    resources :connections, only: [:index, :create, :destroy] do
      put :accept, on: :member
      put :reject, on: :member
    end

    resources :companies, only: [:index, :show, :new, :create, :edit, :update], path: 'organisations/' do
      resources :memberships, only: [:create] do
        delete :destroy, on: :collection
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end
  end

  # ** Routes for users with an artist profile **

  namespace :portfolio do
    resources :artwork_collaborators, only: [] do
      patch :accept, on: :member
      patch :reject, on: :member
    end

    resources :series  do
      get :rearrange, on: :member
      patch :set_order, on: :member
      patch :set_cover, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member

      resources :artworks, only: [:index, :update, :destroy] do
        delete :bulk_destroy, on: :collection
        patch :bulk_update, on: :collection
        post :document_bulk_upload, on: :collection
      end
    end

    resources :artworks, only: [] do
      get :upload, on: :collection
      post :bulk_upload, on: :collection
      post :bulk_group, on: :collection
    end
  end

  # ** Routes for administrators **

  namespace :admin do
    namespace :audits do
      resources :media, :subjects, :specialisations do
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end

    resources :companies, only: [:index, :edit, :update], path: 'organisations/'

    resources :events, only: :index

    resources :users, only: [:index, :show] do
      put :activate, on: :member
      put :deactivate, on: :member
    end

    resources :feeds, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < Admin::BaseController

    def index
      @companies = Company.all.map { |c| CompanyDecorator.new(c) }
    end

    def edit
      @company = Company.find(params[:id])
    end

    def update
      @company = Company.find(params[:id])
      if @company.update_attributes(company_params)
        redirect_to admin_companies_path
      else
        flash[:error] = @company.errors.full_messages.to_sentence
        render :edit
      end
    end

    private

    def company_params
      params.require(:company).permit(
        :image_url, :name, :motto, :location, :established_in,
        :address, :opening_time, :closing_time, :contact,
        :about_us, :facebook, :twitter, :instagram
      )
    end

  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  JS_ASSETS = %w(application companies).freeze

  before_action :require_login
  before_action :prepare_company, only: [:show, :join, :leave, :follow, :unfollow]

  def index
    @companies = Company.includes(:owner).active.page(params[:page]).per(9)
    render :reload if request.xhr?
  end

  def show
    @company = CompanyDecorator.new(@company)
    @company_presenter = CompanyPresenter.new(@company.id)
  end

  def join
    @membership = @company.company_memberships.find_or_initialize_by(user_id: current_user.id)

    if @membership.new_record? && @membership.save
      redirect_to company_path(@company), notice: 'You have joined the company'
    else
      redirect_to company_path(@company), alert: 'You already joined the company'
    end
  end

  def leave
    @membership = @company.company_memberships.find_or_initialize_by(user_id: current_user.id)

    if !@membership.new_record? && @membership.destroy
      redirect_to company_path(@company), notice: 'You have left the company'
    else
      redirect_to company_path(@company), alert: 'You are not a member of the company'
    end
  end

  def follow
    @following = @company.company_followers.find_or_initialize_by(user_id: current_user.id)

    if @following.new_record? && @following.save
      redirect_to company_path(@company), notice: "You have followed #{@company.name}"
    else
      redirect_to company_path(@company), alert: 'Something went wrong!'
    end
  end

  def unfollow
    @following = @company.company_followers.find_or_initialize_by(user_id: current_user.id)

    if !@following.new_record? && @following.destroy
      redirect_to company_path(@company), notice: "You no longer follow #{@company.name}"
    else
      redirect_to company_path(@company), alert: 'Something went wrong!'
    end
  end

  private

  def prepare_company
    @company = Company.find(params[:id])
    redirect_to companies_path, flash: { error: 'Invalid Company!' } if @company.pending?
  end

end

app/controllers/my/base_controller.rb
module My
  class BaseController < ApplicationController

    JS_ASSETS = %w(application my_companies my_connections my_profiles my_settings).freeze

    before_action :require_login
    before_action :prepare_user

    private

    def prepare_user
      @user = current_user
    end

  end
end

app/controllers/my/companies_controller.rb
module My
  class CompaniesController < My::BaseController

    def index
      @user = UserDecorator.new(@user)
      @companies = current_user.companies.map { |c| CompanyDecorator.new(c) }
    end

    def new
      @company_form = My::CompanyForm.new
    end

    def create
      @company_form = My::CompanyForm.new(company_form_params)

      if @company_form.save
        redirect_to my_companies_path, notice: 'New organisation created! Stay tuned for more features'
      else
        flash[:error] = @company_form.errors.full_messages.to_sentence
        render :new
      end
    end

    def show
      @company_presenter = My::CompanyPresenter.new(user_id: @user.id, company_id: params[:id])
    end

    def edit
      @company = @user.companies.find(params[:id])
      @company_form = My::CompanyForm.new(existing_company: @company)
    end

    def update
      @company = @user.companies.find(params[:id])
      @company_form = My::CompanyForm.new(company_form_params.merge(existing_company: @company))

      if @company_form.save
        redirect_to my_companies_path
      else
        flash[:error] = @company_form.errors.full_messages.to_sentence
        render :edit
      end
    end

    private

    def company_form_params
      params.require(:my_company_form).permit(company_attributes: company_attributes_whitelist).tap do |params|
        params[:company_attributes][:owner_id] = current_user.id
      end
    end

    def company_attributes_whitelist
      [
        :image_url, :name, :motto, :country, :state, :established_in, :address_1, :address_2, :contact, :about_us, :postcode,
        :facebook, :twitter, :instagram, :description, :country, :state, :phone, :email, :location,
        :position, :website, :opening_time, :closing_time, organization_type_ids: []
      ]
    end

  end
end

app/controllers/my/connections_controller.rb
module My
  class ConnectionsController < My::BaseController
    before_action :prepare_friend, only: [:create, :accept, :reject, :destroy]

    def index
      @user = UserDecorator.new(@user)
      @friends = current_user.friends.map { |u| UserDecorator.new(u) }.sort_by(&:name)
      @requests = current_user.pending_friends.map { |p| UserDecorator.new(p) }
    end

    def create
      @connection = current_user.connections.build(friend: @friend)
      if @connection.save
        redirect_to :back, notice: 'Connection has been requested'
      else
        redirect_to :back, alert: 'Connection already requested.'
      end
    end

    def accept
      connection = Connection.find_by(friend_id: current_user.id, user_id: @friend.id)
      if connection.pending?
        connection.accept!
        redirect_to my_connections_path, notice: 'Connection accepted.'
      else
        redirect_to my_connections_path, alert: 'Connection is already accepted.'
      end
    end

    def reject
      connection = Connection.find_by(friend_id: current_user.id, user_id: @friend.id)
      if connection.pending?
        connection.reject!
        redirect_to my_connections_path, notice: 'Connection rejected.'
      else
        redirect_to my_connections_path, alert: 'Connection is already rejected.'
      end
    end

    def destroy
      @connection = current_user.connections.accepted.find_by(friend: @friend) ||
                    current_user.passive_connections.accepted.find_by(user: @friend)
      if @connection&.destroy
        redirect_to my_connections_path, notice: 'Connection Removed'
      else
        redirect_to my_connections_path, alert: 'Connection is already disconnected.'
      end
    end

    private

    def prepare_friend
      @friend = User.find(params[:id])
    end

  end
end

app/controllers/my/feeds_controller.rb
module My
  class FeedsController < My::BaseController
    def show
      friends = @user.friends
      feed_items = FeedItem.includes(:user, :artwork).where(user: friends).order(created_at: :desc)
      @feed_items = FeedItemDecorator.wrap_all(feed_items)
    end
  end
end

app/controllers/my/invites_controller.rb
module My
  class InvitesController < My::BaseController
    def create
      @invite = InvitationMailer.invite(params[:email], params[:full_name], @user).deliver_later
      redirect_to root_path, notice: "Your invite to #{params[:full_name]} (#{params[:email]}) was successfully sent!"
    end
  end
end

app/controllers/my/memberships_controller.rb
module My
  class MembershipsController < My::BaseController

    before_action :set_company, only: [:create, :destroy, :approve, :reject]

    def create
      @membership = @company.company_memberships.build(user_id: params[:user_id])
      if @membership.save
        redirect_to my_company_path(@company), notice: 'User added to company!'
      else
        redirect_to my_company_path(@company), alert: 'Something went wrong. Please try again!'
      end
    end

    def destroy
      @membership = @company.company_memberships.find_or_initialize_by(user_id: params[:member_id])

      if !@membership.new_record? && @membership.destroy
        redirect_to my_company_path(@company), notice: 'User was removed from company!'
      else
        redirect_to my_company_path(@company), alert: 'Something went wrong. Please try again!'
      end
    end

    def approve
      @membership = @company.company_memberships.find_by(id: params[:id])

      if @membership.approve!
        redirect_to :back, notice: 'User approved!'
      else
        redirect_to :back, alert: 'Something went wrong. Please try again!'
      end
    end

    def reject
      @membership = @company.company_memberships.find_by(id: params[:id])

      if @membership.reject!
        redirect_to :back, notice: 'User rejected!'
      else
        redirect_to :back, alert: 'Something went wrong. Please try again!'
      end
    end

    private

    def set_company
      @company = @user.companies.find(params[:company_id])
    end

  end
end

app/controllers/my/passwords_controller.rb
module My
  class PasswordsController < My::BaseController
    before_action :authenticate_user, only: [:update]

    def show
    end

    def update
      if @user.update(user_params.except(:current_password))
        redirect_to my_settings_path, notice: 'Your password has been changed'
      else
        redirect_to my_settings_path, alert: 'Passwords do not match!'
      end
    end

    private

    def user_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end

    def authenticate_user
      @user = User.authenticate(current_user.email, user_params[:current_password])
      redirect_to my_settings_path, alert: 'Current password does not match!' unless @user.present?
    end
  end
end

app/controllers/my/profiles_controller.rb
module My
  class ProfilesController < My::BaseController

    def edit
      @user = ProfilePresenter.new(@user.id).user
      @profile_form = My::ProfileForm.new(@user)
    end

    def update
      update_service_call = UpdateUserService.new(@user, user_params).call

      if update_service_call.success?
        redirect_to @user.artist? ? artist_path(@user) : professional_path(@user), notice: 'Your profile has been updated'
      else
        flash[:error] = " Please review your form and make sure all fields marked as red are not empty"
        redirect_to edit_my_profile_path(errors: @user.errors.messages)
      end
    end

    private

    def user_params
      params.require(:my_profile_form).permit(
        user_attributes: [
          :tagline, :profile_image_url, :statement, :link, :interest, :skills, :language, :language_level, :current_status, :commission, :facebook_link, :twitter_link, :instagram_link, :institution, :education_level, :education_grade, :exhibit_country, :based_state, :based_country, :based_location, :nationality_country, :field_of_study, :residency_status, :other_status,
          artist_status_text: [],
          professional_status_text: [],
          representative_ids: [],
          educations_attributes: [:current, :location, :start_month, :start_year, :end_month, :end_year, :institution, :other_institution, :education_level, :education_grade, :field_of_study, :education_description, :state, :country, :id, :_destroy],
          awards_attributes: [:location, :title, :month, :year, :country, :state, :awarding_body, :prize, :pdf_url, :id, :_destroy],
          residencies_attributes: [:location, :start_month, :start_year, :end_month, :end_year, :current, :body, :title, :country, :state, :id, :_destroy],
          experiences_attributes: [:location, :start_month, :start_year, :end_month, :end_year, :current, :position, :company_id, :state, :country, :category, :job_type, :description, :link, :id, :company_name, :_destroy],
          exhibitions_attributes: [:pdf_filename, :location, :involvement_string, :record_start_year, :record_end_year, :start_month, :end_month, :start_year, :end_year, :title, :category, :venue_id, :state, :country, :pdf_url, :id, :_destroy],
          bibliographies_attributes: [:pdf_filename, :volume, :review_of, :location, :title, :publication_title, :publisher, :edition, :author, :page_number, :source_type, :link, :participation, :publication_city, :publication_country, :editor, :issue, :pdf_url, :attachment_url, :day, :month, :year, :id, :_destroy],
          publications_attributes: [:pdf_filename, :location, :volume, :review_of, :participation, :category, :title, :publication_title, :country, :state, :day, :month, :year, :publisher, :edition, :editor, :issue, :page_numbers, :link, :pdf_url, :attachment_url, :id, :_destroy],
          participations_attributes: [:month, :year, :title, :description, :link, :id, :_destroy],
          collections_attributes: [:name, :id, :_destroy],
          memberships_attributes: [:name, :start_date, :end_date, :id, :_destroy],
          media_features_attributes: [:month, :year, :title, :description, :link, :id, :_destroy],
          profile_attributes: [
            :id,
            medium_ids: [],
            subject_ids: [],
            interest_ids: [],
            skill_ids: [],
            specialisation_ids: [],
            service_ids: [],
            language_proficiencies_attributes: [:id, :language_id, :level, :_destroy]
          ]
        ]
      )
    end
  end

end

app/helpers/company_helper.rb
module CompanyHelper

  def image_url(company, width, height, fit)
    return "#{company.image_url}/convert?w=#{width}&h=#{height}&fit=#{fit}" if company.image_url.present?
    email_to_gravatar(company.owner.email)
  end

end

app/views/my/companies/_company.html.slim
.col-xs-12.col-md-3.col-lg-3.text-center
  .card
    header
      = link_to company_path(company) do
        .row
          .col-xs-12
            .img-container
              = image_tag company.image_url, width: 120, height: 120
        .row
          .col-xs-12
            h3.organisation_name = company.name
            h4.organisation_location = company.location
    footer
      .networking
        - if current_user == company.owner
          = link_to 'Edit', edit_my_company_path(company), class: 'btn-user-action'
        - else
          - if current_user.following_companies.collect(&:id).include?(company.id)
            = link_to 'Unfollow', unfollow_company_path(company), method: :patch, class: 'btn-user-action-connected'
          - else
            = link_to 'Follow', follow_company_path(company), method: :patch, class: 'btn-user-action'

app/views/my/companies/_form.html.slim
= company.input :name, label: false, label: "Name of Organization *"
= company.input :established_in, label: 'Established', as: :date, order: [:year], start_year: 1936, end_year: Date.today.year
label What type of organisation is this? * (<i>Please select atleast one </i>)
= company.input :organization_type_ids, label: false, as: :check_boxes, collection: @company_form.options_for_public_organization_type
= company.input :organization_type_ids, collection: @company_form.options_for_private_organization_type, include_hidden: false, placeholder: 'Add Other Organization Type', input_html: { multiple: true, data: { klass: 'OrganizationType', selectize_organisation_type: true, url: my_tags_path(format: :json) } }, wrapper: :selectize
= company.input :about_us, as: :text, label: 'Organisation Description *', input_html: { maxlength: 1000, rows: 12 }
= company.input :website
= company.input :facebook
= company.input :twitter
= company.input :instagram
= company.input :address_1, label: 'Address Line 1 *'
= company.input :address_2, label: 'Address Line 2'
= company.input :location, label: "City, Country *", input_html: { class: "google-places-autocomplete", placeholder: "City, Country" }
= company.hidden_field :country, class: "location-country"
= company.hidden_field :state, class: "location-state"
= company.input :postcode, label: 'Postcode *'
label Opening Hours
.form-group
  .form-inline
    = company.input :opening_time, label: false, prompt: true, minute_step: 15
    span &ndash;
    = company.input :closing_time, label: false, prompt: true, minute_step: 15
label Contact Us *
= company.input :email, label: false, placeholder: 'Email *'
= company.input :phone, label: false, placeholder: 'Phone Number (+60193477620)'

app/views/my/companies/edit.html.slim
.row
  .col-xs-10.col-xs-offset-1
    h1 Edit Organization
    = simple_form_for @company_form, url: my_company_path, method: :patch do |f|
      = f.simple_fields_for :company do |company|
        .form-group
          .text-center
            = image_tag image_url(company.object, 160, 160, ''), size: '160x160'
          .col-xs-12.text-center
            .form-group
              = company.input_field :image_url, { type: 'filepicker-dragdrop',data: { fp_option_modal: false, fp_multiple: true,fp_mimetypes: 'image/*', fp_apikey: ENV["FILEPICKER_API_KEY"],fp_drag_class: 'upload-pane', fp_button_class: 'hidden', fp_drag_text: 'Upload Image' } }
        = render 'form', company: company
      = f.submit 'Save', class: 'btn btn-default'

app/views/my/companies/index.html.slim
nav.row
  .cta
    = link_to 'Create New Organisation', new_my_company_path, class: 'btn btn-primary pull-right'

= render 'shared/user_header', user: @user

.cards
  = render @companies

app/views/my/companies/new.html.slim
.row
  .col-xs-10.col-xs-offset-1
    h1 Create New Organisation
    = simple_form_for @company_form, url: { action: 'create' }, method: 'post' do |f|
      = f.simple_fields_for :company do |company|
        .text-center
          .form-group
            = company.input_field :image_url, { type: 'filepicker-dragdrop',data: { fp_option_modal: false, fp_multiple: true,fp_mimetypes: 'image/*', fp_apikey: ENV["FILEPICKER_API_KEY"],fp_drag_class: 'upload-pane', fp_button_class: 'hidden', fp_drag_text: 'Upload Image' } }
        = render 'form', company: company
        = f.submit 'Submit', class: 'btn btn-default'

app/views/my/companies/show.html.slim
.row
  .col-xs-12
    h1 Manage Your Organisation
    .table-responsive
      table.table.table-hover
        thead
          tr
            th First Name
            th Last Name
            th Email
            th User Type
            th Status
            th Action
        tbody
          - @company_presenter.memberships.each do |membership|
            tr
              td = membership.user.first_name.titleize
              td = membership.user.last_name.titleize
              td = membership.user.email
              td = membership.user.role.titleize
              td = membership.state.titleize
              - if membership.pending?
                td
                  ul.list-inline
                    li = link_to 'Approve', approve_my_company_membership_path(@company_presenter.company, membership.id), method: :patch, class: 'btn btn-info'
                    li = link_to 'Reject', reject_my_company_membership_path(@company_presenter.company, membership.id), method: :patch, class: 'btn btn-warning'
              - else
                td = link_to 'Remove', my_company_memberships_path(company_id: @company_presenter.company, member_id: membership.user_id), method: :delete, class: 'btn btn-info'