config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/dbadmin', as: 'rails_admin'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  root to: 'sessions#new'

  # ** Routes for Errors **
  match "/404", :to => "exception#not_found", :via => :all
  match "/500", :to => "exception#internal_server_error", :via => :all

  # ** Routes for public visitors **

  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about', to: 'pages#about'
  get 'interest', to: 'pages#about'
  get 'contact-us', to: 'pages#contact_us'
  get 'privacy-policy', to: 'pages#privacy_policy'
  get 'terms-and-conditions', to: 'pages#terms_and_conditions'

  post 'interest', to: 'contacts#interest'
  post 'enquiry', to: 'contacts#enquiry'

  resources :registrations, only: [:new, :create] do
    get :confirm_email, on: :member
  end

  resources :password_resets, only: [:create, :edit, :update]

  # ** Routes for users with accounts **
  resources :opportunities

  resources :events do
    patch :add_to_profile, on: :member
  end

  resources :artists, only: [:index, :show] do
    resources :series, only: [:show]
    resources :artworks, only: [:show, :index]
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :professionals, only: [:index, :show] do
    resources :networks, only: [:index]
    resources :organisations, only: [:index]
  end

  resources :companies, only: [:index, :show], path: 'organisations/' do
    patch :join, on: :member
    patch :leave, on: :member
    patch :follow, on: :member
    patch :unfollow, on: :member
  end

  resources :locations, only: [:show]

  namespace :my do
    resource :tags, only: [:create]

    resource :invite, only: [:create]

    resource :feed, only: [:show]

    resource :profile, only: [:edit, :update]

    resource :settings, only: [:show, :update] do
      get :account
      put :deactivate, on: :member
    end

    resource :password, only: [:show, :update]

    resources :connections, only: [:index, :create, :destroy] do
      put :accept, on: :member
      put :reject, on: :member
    end

    resources :companies, only: [:index, :show, :new, :create, :edit, :update], path: 'organisations/' do
      resources :memberships, only: [:create] do
        delete :destroy, on: :collection
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end
  end

  # ** Routes for users with an artist profile **

  namespace :portfolio do
    resources :artwork_collaborators, only: [] do
      patch :accept, on: :member
      patch :reject, on: :member
    end

    resources :series  do
      get :rearrange, on: :member
      patch :set_order, on: :member
      patch :set_cover, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member

      resources :artworks, only: [:index, :update, :destroy] do
        delete :bulk_destroy, on: :collection
        patch :bulk_update, on: :collection
        post :document_bulk_upload, on: :collection
      end
    end

    resources :artworks, only: [] do
      get :upload, on: :collection
      post :bulk_upload, on: :collection
      post :bulk_group, on: :collection
    end
  end

  # ** Routes for administrators **

  namespace :admin do
    namespace :audits do
      resources :media, :subjects, :specialisations do
        patch :approve, on: :member
        patch :reject, on: :member
      end
    end

    resources :companies, only: [:index, :edit, :update], path: 'organisations/'

    resources :events, only: :index

    resources :users, only: [:index, :show] do
      put :activate, on: :member
      put :deactivate, on: :member
    end

    resources :feeds, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :members, class_name: 'User', foreign_key: 'company_id'

  has_many :exhibitions, foreign_key: 'venue_id'
  has_many :represented_exhibitions, class_name: 'Exhibition', foreign_key: 'representation_id'

  has_many :company_memberships
  has_many :members, through: :company_memberships, source: :user

  has_many :approved_members, -> { where company_memberships: { state: 1 } }, through: :company_memberships, source: :user

  has_many :events
  has_many :opportunities

  has_many :company_followers
  has_many :followers, through: :company_followers, source: :user

  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  validates :name, presence: true
  validates :address_1, presence: true
  validates :location, presence: true
  validates :postcode, presence: true
  validates :organization_types, presence: true
  validates :about_us, presence: true
  validates :name, uniqueness: true
  #validates :image_url, presence: true, on: :update
  validates :owner, presence: true, if: :owner_id
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, if: :email
  #validates :phone, format: { with: /\A^\+(?:[0-9] ?){6,14}[0-9]$\z/, message: 'Please format your phone number with a country code (ie. +44)' }, if: :phone

  enum position: [:owner, :employee]

  scope :pending, -> { where(owner: nil) }
  scope :active, -> { where.not(owner: nil) }

  def active?
    owner.present?
  end

  def pending?
    !active?
  end

  def organization_types
    OrganizationType.approved.where(id: organization_type_ids).pluck(:name)
  end

end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < Admin::BaseController

    def index
      @companies = Company.all.map { |c| CompanyDecorator.new(c) }
    end

    def edit
      @company = Company.find(params[:id])
    end

    def update
      @company = Company.find(params[:id])
      if @company.update_attributes(company_params)
        redirect_to admin_companies_path
      else
        flash[:error] = @company.errors.full_messages.to_sentence
        render :edit
      end
    end

    private

    def company_params
      params.require(:company).permit(
        :image_url, :name, :motto, :location, :established_in,
        :address, :opening_time, :closing_time, :contact,
        :about_us, :facebook, :twitter, :instagram
      )
    end

  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  JS_ASSETS = %w(application companies).freeze

  before_action :require_login
  before_action :prepare_company, only: [:show, :join, :leave, :follow, :unfollow]

  def index
    @companies = Company.includes(:owner).active.page(params[:page]).per(9)
    render :reload if request.xhr?
  end

  def show
    @company = CompanyDecorator.new(@company)
    @company_presenter = CompanyPresenter.new(@company.id)
  end

  def join
    @membership = @company.company_memberships.find_or_initialize_by(user_id: current_user.id)

    if @membership.new_record? && @membership.save
      redirect_to company_path(@company), notice: 'You have joined the company'
    else
      redirect_to company_path(@company), alert: 'You already joined the company'
    end
  end

  def leave
    @membership = @company.company_memberships.find_or_initialize_by(user_id: current_user.id)

    if !@membership.new_record? && @membership.destroy
      redirect_to company_path(@company), notice: 'You have left the company'
    else
      redirect_to company_path(@company), alert: 'You are not a member of the company'
    end
  end

  def follow
    @following = @company.company_followers.find_or_initialize_by(user_id: current_user.id)

    if @following.new_record? && @following.save
      redirect_to company_path(@company), notice: "You have followed #{@company.name}"
    else
      redirect_to company_path(@company), alert: 'Something went wrong!'
    end
  end

  def unfollow
    @following = @company.company_followers.find_or_initialize_by(user_id: current_user.id)

    if !@following.new_record? && @following.destroy
      redirect_to company_path(@company), notice: "You no longer follow #{@company.name}"
    else
      redirect_to company_path(@company), alert: 'Something went wrong!'
    end
  end

  private

  def prepare_company
    @company = Company.find(params[:id])
    redirect_to companies_path, flash: { error: 'Invalid Company!' } if @company.pending?
  end

end

app/controllers/my/companies_controller.rb
module My
  class CompaniesController < My::BaseController

    def index
      @user = UserDecorator.new(@user)
      @companies = current_user.companies.map { |c| CompanyDecorator.new(c) }
    end

    def new
      @company_form = My::CompanyForm.new
    end

    def create
      @company_form = My::CompanyForm.new(company_form_params)

      if @company_form.save
        redirect_to my_companies_path, notice: 'New organisation created! Stay tuned for more features'
      else
        flash[:error] = @company_form.errors.full_messages.to_sentence
        render :new
      end
    end

    def show
      @company_presenter = My::CompanyPresenter.new(user_id: @user.id, company_id: params[:id])
    end

    def edit
      @company = @user.companies.find(params[:id])
      @company_form = My::CompanyForm.new(existing_company: @company)
    end

    def update
      @company = @user.companies.find(params[:id])
      @company_form = My::CompanyForm.new(company_form_params.merge(existing_company: @company))

      if @company_form.save
        redirect_to my_companies_path
      else
        flash[:error] = @company_form.errors.full_messages.to_sentence
        render :edit
      end
    end

    private

    def company_form_params
      params.require(:my_company_form).permit(company_attributes: company_attributes_whitelist).tap do |params|
        params[:company_attributes][:owner_id] = current_user.id
      end
    end

    def company_attributes_whitelist
      [
        :image_url, :name, :motto, :country, :state, :established_in, :address_1, :address_2, :contact, :about_us, :postcode,
        :facebook, :twitter, :instagram, :description, :country, :state, :phone, :email, :location,
        :position, :website, :opening_time, :closing_time, organization_type_ids: []
      ]
    end

  end
end

app/helpers/company_helper.rb
module CompanyHelper

  def image_url(company, width, height, fit)
    return "#{company.image_url}/convert?w=#{width}&h=#{height}&fit=#{fit}" if company.image_url.present?
    email_to_gravatar(company.owner.email)
  end

end

app/views/companies/_artist.html.slim
.card
  .avatar
    = link_to profile_path(user), target: '_blank' do
      = image_tag profile_image_url(user, 160, 160, 'crop'), size: '160x160'
  .details
    h6 = user.full_name

app/views/companies/_company.html.slim
.col-xs-12.col-md-3.col-lg-3.text-center
  .card
    header
      = link_to company_path(company) do
        .row
          .col-xs-12
            .img-container
              = image_tag company.image_url
        .row
          .col-xs-12
            h3.organisation_name = company.name
            h4.organisation_location = company.location
    footer
      .networking
        - if current_user == company.owner
          = link_to 'Edit', edit_my_company_path(company), class: 'btn-user-action'
        - else
          - if current_user.following_companies.collect(&:id).include?(company.id)
            = link_to 'Unfollow', unfollow_company_path(company), method: :patch, class: 'btn-user-action-connected'
          - else
            = link_to 'Follow', follow_company_path(company), method: :patch, class: 'btn-user-action'

app/views/companies/_events.html.slim
.company-events-index
  .row
    - @company.events.each do |event|
      .col-xs-12.col-md-6.col-lg-6.text-center
        .card
          header
            = link_to event_path(event) do
              .row
                .col-xs-12
                  .img-container
                    = image_tag event.cover_image_url
              .row
                .col-xs-12
                  h3.event_name = event.name
                  h4.event_location = event.location
                  h4.event_company = event.company.try(:name)
                  h4.event_type = event.event_type
                  - if event.end_date.present?
                    h4.event_date = "#{event.start_date} - #{event.end_date}"
                  - else
                    h4.event_date = "#{event.start_date}"

app/views/companies/_opportunities.html.slim
.row
  .col-xs-12
    #accordion.panel-group aria-multiselectable='true' role='tablist'
      - @company.opportunities.each_with_index do |opportunity, index|
        .panel.panel-default
          .panel-heading role='tab' data-toggle='collapse' href="#collapse-opportunity-#{opportunity.id}" id="heading-opportunity-#{opportunity.id}"
            h4.panel-title
              a aria-controls="collapse-opportunity-#{opportunity.id}" aria-expanded='true' data-parent='#accordion'
                label.opportunity-title = opportunity.title
                .indicator.pull-right.opportunity-status = opportunity.status
          .panel-collapse.collapse aria-labelledby='heading-opportunity' role='tabpanel' id="collapse-opportunity-#{opportunity.id}"
            .panel-body
              p = simple_format opportunity.description
              - if opportunity.created_by == current_user
                = link_to "Edit Opportunity", edit_opportunity_path(opportunity), class: "btn btn-default pull-right"

app/views/companies/_professional.html.slim
.card
  .avatar
    = link_to profile_path(user_map[:professional]), target: '_blank' do
      = image_tag profile_image_url(user_map[:professional], 160, 160, 'crop'), size: '160x160'
  .details
    h6 = user_map[:professional].full_name
    - if user_map[:experience].present?
      p = user_map[:experience].position.camelcase
      p = " Since #{user_map[:experience].start_year}"

app/views/companies/index.html.slim
= render 'shared/discover'
.row
  = render partial: 'company', collection: @companies.map { |c| CompanyDecorator.new(c) }
.row
  .col-xs-12
    .text-center
      - unless @companies.current_page == @companies.total_pages
        #load-more
          = link_to 'Load More', companies_path(page: @companies.current_page + 1), remote: true, class: 'btn btn-default'

app/views/companies/reload.js.erb
$('.cards').append("<%=j render(partial: 'company', collection: @companies) %>");

<% if @companies.current_page == @companies.total_pages %>
  $('#load-more').remove();
<% else %>
  $('#load-more a').attr('href', '<%= companies_path(page: @companies.current_page + 1) %>');
<% end %>

app/views/companies/show.html.slim
section
  .row.company-header.well
    .col-md-6
      .img-container
        = image_tag @company.image_url
    .col-md-6
      h1.text-right.company-title = @company.name
      h4.text-right = @company.organization_types.join(', ')
      h4.text-right = @company.location
      h4.text-right = "Established #{@company.established_in.year}"
      ul.actions
        - if current_user == @company.owner
          li = link_to 'Edit', edit_my_company_path(@company), class: 'btn btn-default'
          - if false
            li = link_to 'Manage', my_company_path(@company), class: 'btn btn-default'
        - else
          - if current_user.following_companies.collect(&:id).include?(@company.id)
            li = link_to 'Unfollow', unfollow_company_path(@company), method: :patch, class: 'btn btn-default'
          - else
            li = link_to 'Follow', follow_company_path(@company), method: :patch, class: 'btn btn-default'
.row
  .col-xs-12.col-md-2.company-navigation.well
    ul.tab-lists
      li.about-us-tab.active role="presentation"
        h2
          a aria-controls="home" data-toggle="tab" href="#about_us" role="tab" About Us
      li.events-tab
        h2
          a aria-controls="home" data-toggle="tab" href="#events" role="tab" Events
      li.opportunities-tab
        h2
          a aria-controls="home" data-toggle="tab" href="#opportunities" role="tab" Opportunities
  .col-xs-12.col-md-8
    .tab-content
      #about_us.tab-pane.active role="tabpanel"
        p = @company.about_us.presence || '-'
      #events.tab-pane role="tabpanel"
        = render partial: 'events'
      #opportunities.tab-pane role="tabpanel"
        = render partial: 'opportunities'
  .col-xs-12.col-md-2.well
    ul.company-details
      li
        h2 Address
        - if !@company.address_1.blank? || !@company.address_2.blank?
          p = @company.address_1
          p = @company.address_2
        - else
          p -

      li
        h2 Opening Times
        p = @company.opening_hours
      li
        h2 Contact
        p = @company.phone
        p = @company.email
      li
        ul.social-links.col-xs-12
          - if @company&.facebook.present?
            li = link_to_if @company&.facebook, fa_icon('facebook-official'), @company&.facebook
          - if @company&.twitter.present?
            li = link_to_if @company&.twitter, fa_icon('twitter'), @company&.twitter

          - if @company&.instagram.present?
            li = link_to_if @company&.instagram, fa_icon('instagram'), @company&.instagram